export const GET_ALL_VIDEOGAMES= 'GET_ALL_VIDEOGAMES';
export const GET_VIDEOGAMES_DETAIL= 'GET_VIDEOGAMES_DETAIL';// id
export const GET_ALL_POSTS= 'GET_ALL_POSTS';//
export const GET_NAME_VIDEOGAMES = 'GET_NAME_VIDEOGAMES';
export const ADD_VIDEOGAME= 'ADD_VIDEOGAME';//post
export const UPDATE_VIDEOGAME= 'UPDATE_VIDEOGAME';//put
export const DELETE_VIDEOGAME= 'DELETE_VIDEOGAME';//delete
export const FILTER_GENERS= 'FILTER_GENERS';// por generos traer 
export const FILTER = 'FILTER';
export const FILTER_GENERS_DB='FILTER_GENERS_DB'
export const ORDER_ALFABETICO= 'ORDER_ALFABETICO';//order alfabetico o por raitngs 
export const ORDER_RATINGS= 'ORDER_RATINGS'